### ISSUE TITLE
Redirect url not clear 

### ISSUE THREAD

**Issue by Milimeter** [lukeurban/payu_payment#1]
After reading the documentation on pub.dev the redirect url explanation was not clear and its implementation wasn't understood.Could  perhaps provide more information on the usage and implementation.

**Comment by lukeurban** [comment]
I'll write a more comprehensive explanation in readme.

**Comment by lukeurban** [comment]
@Milimeter So in version 0.0.3. I've added some more explanation about `redirectUrl` in the readme. There is also a bit better documentation for methods and variables. Let me know if this new explanation is clear to you 😉 Thanks for contributing 👍
